"""Language-neutral evidence checks shared by annotation reviewers."""

FORM_STAGE_EVIDENCE_GUIDANCE = """When a candidate shows an inflected or constructed form, inspect the complete submitted sequence from its displayed lemma through every ordered form step and the observed surface; also inspect linked grammar lessons or overlays when they are within your assigned review remit. Compare each step with the actual supplied lesson/function and with the next operation. A non-past intermediate can correctly precede an explicit past transformation: for example, a noun plus copula can first mean “is a son”, then a past marker can yield “was a son”. Do not call that chain inconsistent merely because the final occurrence is past.

Before reporting a form, tense, or meaning issue, name the exact submitted form/step, its label and meaning, the linked lesson or overlay when within your remit, and the concrete mismatch in the transition or final result. Do not report a defect by restating a correct submitted field, and do not claim a required stage or link is missing when it is present. Reject a real defect: for example, a past final surface whose chain stops at the non-past form, a final past stage still glossed as present, a wrong or missing past link, or a linked lesson that does not explain the displayed operation. Apply these checks only where the annotation supplies such a chain or linked analysis; do not invent morphology or require optional analysis."""

FORM_STAGE_COMPLETENESS_GUIDANCE = """Check that every displayed intermediate stage is itself a complete learner-facing form, citation form, or complete clause/construction form supported by the language's reviewed analysis. A label such as “honorific” or “past” does not make a prefinal stem or bound inflection complete: distinguish a complete form from a stem that still requires a clause-ending or connective ending. The final observed surface may be a complete connective/clause form, and a non-final stage may be a complete citation or clause form; compare the exact spelling, linked operation, and next transition rather than guessing from a suffix. Reject ending-only or bare inflectional-stem stages when they are presented as complete forms. Keep the stage meaning about that complete form and keep tense, politeness, or other form information in its separate label. Contrast: a complete citation-form intermediate followed by an observed past connective can be valid; a prefinal stem mislabeled as a complete past/honorific stage is not. Do not demand optional stages, invent morphology, or accept/reject by a language-specific string heuristic.

Judge the scope of each meaning field. A complete predicate stage may use a complete valency-frame gloss such as “regards [X] as [Y]”; do not require the whole sentence's subject, object, and complement to be repeated in every stage meaning. Keep a modifier's own prospective or attributive contribution distinct from the meaning of a larger construction formed with its dependent noun and predicate; do not assign the whole construction's modality to the modifier alone. When passive, result-state, completion, or English past-versus-past-perfect readings are at issue, cite the linked lesson and source timeline that make the submitted meaning incompatible. Do not reject a defensible translation merely because another natural English rendering is also possible. Contrast: “be raised” can describe a passive citation form while “raised” describes a completed modifier; a bare prefinal stem still remains incomplete even when its English gloss looks plausible. Do not turn these checks into mandatory contextual paraphrases or optional-stage requirements."""

SPAN_COMPONENT_MEANING_GUIDANCE = """Keep component and span meanings separate. In Chinese, a segment meaning belongs to that tap and a grammar overlay may carry the meaning of a longer span. In Japanese and Korean, a form-step meaning belongs to its exact displayed form, while a spanning grammar overlay/link may carry the complete construction meaning. A connective, embedded-question, or auxiliary form may depend on following material and need not read as an independent English assertion; describe its own contribution using the lesson or primary reference for that component. Do not copy the overlay's full translation into every component, attribute the whole construction meaning to one auxiliary, or call a supported dependent form incomplete only because the larger clause continues in another tap. Conversely, do not infer a component meaning or identity solely from evidence for the whole construction. Contrast: an embedded “whether X will happen” form followed by “does not know” can combine into a span meaning “X may happen”; the embedded form and the complete span have different meanings. If the component analysis is not supported, leave it uncertain or route it for research rather than inventing a lesson. This scope rule does not excuse a bare stem that still requires an ending to form the displayed stage."""

FORM_STAGE_COMPLETENESS_GUIDANCE += "\n\n" + SPAN_COMPONENT_MEANING_GUIDANCE

FORM_STAGE_COMPLETENESS_GUIDANCE += "\n\n" + "An English relative or participial gloss such as “who knows”, “that knew”, or “having moved” can express a complete modifier's meaning. Its English syntax need not duplicate the source language's grammatical category. Do not call such a gloss a standalone proposition merely because another relative-clause paraphrase is possible. Before claiming that a meaning imports an external subject, object, dependent noun, or predicate, identify the actual extra words or semantic contribution in the submitted meaning; a relative pronoun alone does not import the following head noun or a preceding object. Contrast: “having moved” can describe a completed modifier; “after moving to the capital” imports the following temporal construction or separately annotated destination when those contributions are outside the displayed form. A form-level gloss and a contextual occurrence gloss may differ in tense when the form and source timeline support that distinction; do not require identical wording across these fields."

FORM_STAGE_EVIDENCE_GUIDANCE += "\n\n" + FORM_STAGE_COMPLETENESS_GUIDANCE

# This exact earlier digest already included the complete-stage / prefinal-stem
# criteria. It predates only the later clarification about meaning scope. Keep
# compatibility explicit and narrow so approved reviews need not be repeated
# for that clarification; pre-completeness guidance remains stale.
FORM_STAGE_COMPATIBLE_REVIEW_DIGESTS = frozenset({
    '4f0ac6c6d35d8f450482f608436a9fa57cab7822c0ebf96758f56fe5f9e96a3d',
    # Same complete-form and scope rules before the English-gloss clarification.
    '2da6beaba39d3641ea15f889ed3c139a78ad6cae37a041d523b956a3aebfbf43',
})
