"""Language-neutral evidence checks shared by annotation reviewers."""

FORM_STAGE_EVIDENCE_GUIDANCE = """When a candidate shows an inflected or constructed form, inspect the complete submitted sequence from its displayed lemma through every ordered form step and the observed surface; also inspect linked grammar lessons or overlays when they are within your assigned review remit. Compare each step with the actual supplied lesson/function and with the next operation. A non-past intermediate can correctly precede an explicit past transformation: for example, a noun plus copula can first mean “is a son”, then a past marker can yield “was a son”. Do not call that chain inconsistent merely because the final occurrence is past.

Before reporting a form, tense, or meaning issue, name the exact submitted form/step, its label and meaning, the linked lesson or overlay when within your remit, and the concrete mismatch in the transition or final result. Do not report a defect by restating a correct submitted field, and do not claim a required stage or link is missing when it is present. Reject a real defect: for example, a past final surface whose chain stops at the non-past form, a final past stage still glossed as present, a wrong or missing past link, or a linked lesson that does not explain the displayed operation. Apply these checks only where the annotation supplies such a chain or linked analysis; do not invent morphology or require optional analysis."""

FORM_STAGE_COMPLETENESS_GUIDANCE = """Check that every displayed intermediate stage is itself a complete learner-facing form, citation form, or complete clause/construction form supported by the language's reviewed analysis. A label such as “honorific” or “past” does not make a prefinal stem or bound inflection complete: distinguish a complete form from a stem that still requires a clause-ending or connective ending. The final observed surface may be a complete connective/clause form, and a non-final stage may be a complete citation or clause form; compare the exact spelling, linked operation, and next transition rather than guessing from a suffix. Reject ending-only or bare inflectional-stem stages when they are presented as complete forms. Keep the stage meaning about that complete form and keep tense, politeness, or other form information in its separate label. Contrast: a complete citation-form intermediate followed by an observed past connective can be valid; a prefinal stem mislabeled as a complete past/honorific stage is not. Do not demand optional stages, invent morphology, or accept/reject by a language-specific string heuristic."""

FORM_STAGE_EVIDENCE_GUIDANCE += "\n\n" + FORM_STAGE_COMPLETENESS_GUIDANCE
